### ISSUE TITLE
Server layout

### ISSUE THREAD

**Issue by joegle** [cmusatyalab/dermshare#3]
Hi, My team and I have been working on the dermshare opendiamond implementation. We believe we have all dependency requirements met because each of the services appear to run (autosegementer, simplescope.py, blaster, dermshare.py, diamondd, dermshare_dataretriever.py, etc). 

We split up the services across 4 servers in the following way:
- _scopeserver_ - running simplescope.py 
- _dermclient_ - running dermshare.py
- _jsonblaster_ - running /usr/local/bin/blaster (without reverse proxy)
- _diamond0_ - running diamondd, redis and dermshare_dataretriever.py (with populated data folders)

All these services are 
- listening on 0.0.0.0 with "-l 0.0.0.0" arguments 
- on port 8080 which is mapped to port 80 with iptables 
- running under the same nonroot user

Is this topology recommended? Would it be preferred to group the jsonblaster with _diamond0_ or separate the dataretriever? Are there any junctions where using localhost instead of an IP address in a config file are more supported?  We separated the servers to aid in debugging such as reading logs, distinguishing cookiecutter arguments and scopecookie placements. Thanks

**Comment by bgilbert** [comment]
Again, please use the mailing list.

That topology is a bit odd, but should work.  The scope server and web app don't consume many resources, so they could be on the same machine.  The blaster shouldn't be grouped with diamondd, because a cluster of multiple diamondds only uses a single blaster.  When you scale to multiple diamondds, you'll probably want to move the dataretriever to its own machine (or to the scopeserver/web app machine) to avoid duplicating the data.  In general, you want the dataretriever next to your data, the scopeserver included in the web UI for your data, and the diamondds on machines with a lot of compute cycles.

All config files should be able to accept hostnames as well as IP addresses.
